[View in Colaboratory](https://colab.research.google.com/github/myfellowship/ML-DL-projects/blob/master/Kopi_av_x_ray_data_to_csv.ipynb)

In [0]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/gvsanthu10/Dicom/master/Data_Entry_2017.csv')

In [24]:
data = data.iloc[:,0:2]
data.tail()

             Image Index  Finding Labels
112115  00030801_001.png  Mass|Pneumonia
112116  00030802_000.png      No Finding
112117  00030803_000.png      No Finding
112118  00030804_000.png      No Finding
112119  00030805_000.png      No Finding

In [0]:
data.columns = ['ID', 'labels']

In [0]:
data = data.apply(lambda x: x.str.replace('|',','))

In [27]:
data.head()

                 ID                  labels
0  00000001_000.png            Cardiomegaly
1  00000001_001.png  Cardiomegaly,Emphysema
2  00000001_002.png   Cardiomegaly,Effusion
3  00000002_000.png              No Finding
4  00000003_000.png                  Hernia

In [28]:
df = pd.DataFrame(data)
       

df = df['labels'].str.split('\s*,\s*', expand=True)\
                .stack().str.get_dummies().sum(level=0)
print(df)

        Atelectasis  Cardiomegaly  Consolidation  Edema  Effusion  Emphysema  \
0                 0             1              0      0         0          0
1                 0             1              0      0         0          1
2                 0             1              0      0         1          0
3                 0             0              0      0         0          0
4                 0             0              0      0         0          0
5                 0             0              0      0         0          0
6                 0             0              0      0         0          0
7                 0             0              0      0         0          0
8                 0             0              0      0         0          0
9                 0             0              0      0         0          0
10                0             0              0      0         0          0
11                0             0              0      0         0          0
12                0             0              0      0         0          0
13                0             0              0      0         0          0
14                0             0              0      0         0          0
15                0             0              0      0         0          0
16                0             0              0      0         0          0
17                0             0              0      0         0          0
18                0             0              0      0         0          0
19                0             0              0      0         0          0
20                0             0              0      0         1          0
21                0             0              0      0         0          0
22                0             0              0      0         0          0
23                0             1              0      0         0          0
24                0             0              0      0         0          0
25                0             0              0      0         0          0
26                0             0              0      0         0          1
27                0             0              0      0         0          0
28                0             0              0      0         1          0
29                0             0              0      0         0          0
...             ...           ...            ...    ...       ...        ...
112090            0             0              0      0         1          0
112091            0             0              0      0         1          1
112092            0             1              0      0         1          1
112093            0             1              0      0         1          1
112094            0             1              0      0         1          1
112095            0             1              0      0         1          1
112096            0             0              1      0         0          0
112097            0             0              1      0         0          0
112098            0             0              0      0         0          0
112099            0             0              0      0         0          0
112100            0             0              0      0         0          0
112101            0             0              0      0         0          0
112102            0             0              0      0         0          0
112103            0             0              0      0         0          0
112104            0             0              0      0         0          0
112105            0             0              0      0         0          0
112106            0             0              0      0         0          0
112107            0             0              0      0         0          0
112108            0             0              0      0         0          0
112109            0             0              0      0         0          0
112110            0             0              0      0         0          0
112111            0             0              0      0         0          0
112112            0             0              0      0         0          0
112113            0             0              0      0         0          0
112114            0             0              0      0         0          0
112115            0             0              0      0         0          0
112116            0             0              0      0         0          0
112117            0             0              0      0         0          0
112118            0             0              0      0         0          0
112119            0             0              0      0         0          0

        Fibrosis  Hernia  Infiltration  Mass  No Finding  Nodule  \
0              0       0             0     0           0       0
1              0       0             0     0           0       0
2              0       0             0     0           0       0
3              0       0             0     0           1       0
4              0       1             0     0           0       0
5              0       1             0     0           0       0
6              0       1             0     0           0       0
7              0       1             1     0           0       0
8              0       1             0     0           0       0
9              0       1             0     0           0       0
10             0       1             0     0           0       0
11             0       1             0     0           0       0
12             0       0             0     1           0       1
13             0       0             0     0           1       0
14             0       0             0     0           1       0
15             0       0             0     0           1       0
16             0       0             0     0           1       0
17             0       0             0     0           1       0
18             0       0             0     0           1       0
19             0       0             1     0           0       0
20             0       0             1     0           0       0
21             0       0             0     0           1       0
22             0       0             0     0           1       0
23             0       0             0     0           0       0
24             0       0             0     0           1       0
25             0       0             0     0           0       1
26             0       0             0     0           0       0
27             0       0             1     0           0       0
28             0       0             0     0           0       0
29             0       0             0     0           1       0
...          ...     ...           ...   ...         ...     ...
112090         0       0             0     0           0       0
112091         0       0             0     0           0       0
112092         0       0             0     0           0       0
112093         0       0             0     0           0       0
112094         0       0             0     0           0       0
112095         0       0             0     0           0       0
112096         0       0             0     0           0       0
112097         0       0             0     0           0       0
112098         0       0             0     0           1       0
112099         0       0             0     0           1       0
112100         0       0             1     0           0       0
112101         0       0             0     0           1       0
112102         0       0             0     0           1       0
112103         0       0             0     0           1       0
112104         0       0             0     0           1       0
112105         0       0             0     0           1       0
112106         0       0             0     1           0       1
112107         0       0             0     0           1       0
112108         0       0             0     0           0       0
112109         0       0             0     0           1       0
112110         0       0             0     0           1       0
112111         0       0             0     0           1       0
112112         0       0             0     0           1       0
112113         0       0             0     0           1       0
112114         0       0             0     0           1       0
112115         0       0             0     1           0       0
112116         0       0             0     0           1       0
112117         0       0             0     0           1       0
112118         0       0             0     0           1       0
112119         0       0             0     0           1       0

        Pleural_Thickening  Pneumonia  Pneumothorax
0                        0          0             0
1                        0          0             0
2                        0          0             0
3                        0          0             0
4                        0          0             0
5                        0          0             0
6                        0          0             0
7                        0          0             0
8                        0          0             0
9                        0          0             0
10                       0          0             0
11                       0          0             0
12                       0          0             0
13                       0          0             0
14                       0          0             0
15                       0          0             0
16                       0          0             0
17                       0          0             0
18                       0          0             0
19                       0          0             0
20                       0          0             0
21                       0          0             0
22                       0          0             0
23                       0          0             0
24                       0          0             0
25                       0          0             0
26                       0          0             0
27                       0          0             0
28                       0          0             0
29                       0          0             0
...                    ...        ...           ...
112090                   0          0             0
112091                   0          0             1
112092                   0          0             1
112093                   0          0             1
112094                   0          0             1
112095                   0          0             0
112096                   0          0             0
112097                   1          0             0
112098                   0          0             0
112099                   0          0             0
112100                   0          0             0
112101                   0          0             0
112102                   0          0             0
112103                   0          0             0
112104                   0          0             0
112105                   0          0             0
112106                   0          0             0
112107                   0          0             0
112108                   1          0             0
112109                   0          0             0
112110                   0          0             0
112111                   0          0             0
112112                   0          0             0
112113                   0          0             0
112114                   0          0             0
112115                   0          1             0
112116                   0          0             0
112117                   0          0             0
112118                   0          0             0
112119                   0          0             0

[112120 rows x 15 columns]

In [12]:
df.head()

,Atelectasis,Cardiomegaly,Consolidation,Edema,Effusion,Emphysema,Fibrosis,Hernia,Infiltration,Mass,No Finding,Nodule,Pleural_Thickening,Pneumonia,Pneumothorax
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [0]:
df=df.iloc[:,9:]

In [30]:
df.iloc[:,:3]

        Mass  No Finding  Nodule
0          0           0       0
1          0           0       0
2          0           0       0
3          0           1       0
4          0           0       0
5          0           0       0
6          0           0       0
7          0           0       0
8          0           0       0
9          0           0       0
10         0           0       0
11         0           0       0
12         1           0       1
13         0           1       0
14         0           1       0
15         0           1       0
16         0           1       0
17         0           1       0
18         0           1       0
19         0           0       0
20         0           0       0
21         0           1       0
22         0           1       0
23         0           0       0
24         0           1       0
25         0           0       1
26         0           0       0
27         0           0       0
28         0           0       0
29         0           1       0
...      ...         ...     ...
112090     0           0       0
112091     0           0       0
112092     0           0       0
112093     0           0       0
112094     0           0       0
112095     0           0       0
112096     0           0       0
112097     0           0       0
112098     0           1       0
112099     0           1       0
112100     0           0       0
112101     0           1       0
112102     0           1       0
112103     0           1       0
112104     0           1       0
112105     0           1       0
112106     1           0       1
112107     0           1       0
112108     0           0       0
112109     0           1       0
112110     0           1       0
112111     0           1       0
112112     0           1       0
112113     0           1       0
112114     0           1       0
112115     1           0       0
112116     0           1       0
112117     0           1       0
112118     0           1       0
112119     0           1       0

[112120 rows x 3 columns]

In [0]:
predata = pd.concat([data, df], axis=1)
predata = predata.drop(['labels'], axis=1)

In [35]:
predata.head()

                 ID  Mass  No Finding  Nodule
0  00000001_000.png     0           0       0
1  00000001_001.png     0           0       0
2  00000001_002.png     0           0       0
3  00000002_000.png     0           1       0
4  00000003_000.png     0           0       0

In [0]:
predata=predata.drop(['Pleural_Thickening','Pneumonia', 'Pneumothorax'], axis=1)

In [0]:
predata.to_csv('out.csv')

In [38]:
!ls

datalab  out.csv  sample_data

In [0]:
from google.colab import files

files.download('out.csv')

In [41]:
predata.describe()

                Mass     No Finding         Nodule
count  112120.000000  112120.000000  112120.000000
mean        0.051570       0.538361       0.056466
std         0.221158       0.498529       0.230821
min         0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000
50%         0.000000       1.000000       0.000000
75%         0.000000       1.000000       0.000000
max         1.000000       1.000000       1.000000

In [46]:
pd.read_csv('out.csv')

        Unnamed: 0                ID  Mass  No Finding  Nodule
0                0  00000001_000.png     0           0       0
1                1  00000001_001.png     0           0       0
2                2  00000001_002.png     0           0       0
3                3  00000002_000.png     0           1       0
4                4  00000003_000.png     0           0       0
5                5  00000003_001.png     0           0       0
6                6  00000003_002.png     0           0       0
7                7  00000003_003.png     0           0       0
8                8  00000003_004.png     0           0       0
9                9  00000003_005.png     0           0       0
10              10  00000003_006.png     0           0       0
11              11  00000003_007.png     0           0       0
12              12  00000004_000.png     1           0       1
13              13  00000005_000.png     0           1       0
14              14  00000005_001.png     0           1       0
15              15  00000005_002.png     0           1       0
16              16  00000005_003.png     0           1       0
17              17  00000005_004.png     0           1       0
18              18  00000005_005.png     0           1       0
19              19  00000005_006.png     0           0       0
20              20  00000005_007.png     0           0       0
21              21  00000006_000.png     0           1       0
22              22  00000007_000.png     0           1       0
23              23  00000008_000.png     0           0       0
24              24  00000008_001.png     0           1       0
25              25  00000008_002.png     0           0       1
26              26  00000009_000.png     0           0       0
27              27  00000010_000.png     0           0       0
28              28  00000011_000.png     0           0       0
29              29  00000011_001.png     0           1       0
...            ...               ...   ...         ...     ...
112090      112090  00030786_000.png     0           0       0
112091      112091  00030786_001.png     0           0       0
112092      112092  00030786_002.png     0           0       0
112093      112093  00030786_003.png     0           0       0
112094      112094  00030786_004.png     0           0       0
112095      112095  00030786_005.png     0           0       0
112096      112096  00030786_006.png     0           0       0
112097      112097  00030786_007.png     0           0       0
112098      112098  00030787_000.png     0           1       0
112099      112099  00030788_000.png     0           1       0
112100      112100  00030789_000.png     0           0       0
112101      112101  00030790_000.png     0           1       0
112102      112102  00030791_000.png     0           1       0
112103      112103  00030791_001.png     0           1       0
112104      112104  00030792_000.png     0           1       0
112105      112105  00030792_001.png     0           1       0
112106      112106  00030793_000.png     1           0       1
112107      112107  00030794_000.png     0           1       0
112108      112108  00030795_000.png     0           0       0
112109      112109  00030796_000.png     0           1       0
112110      112110  00030797_000.png     0           1       0
112111      112111  00030798_000.png     0           1       0
112112      112112  00030799_000.png     0           1       0
112113      112113  00030800_000.png     0           1       0
112114      112114  00030801_000.png     0           1       0
112115      112115  00030801_001.png     1           0       0
112116      112116  00030802_000.png     0           1       0
112117      112117  00030803_000.png     0           1       0
112118      112118  00030804_000.png     0           1       0
112119      112119  00030805_000.png     0           1       0

[112120 rows x 5 columns]

In [51]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once in a notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once in a notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Create & upload a file.
uploaded = drive.CreateFile({'title': 'out.csv'})
uploaded.SetContentFile('out.csv')
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

Uploaded file with ID 1S2GICVZpNTBHrtgKa1l4wDCiXLgfxq-r